### ISSUE TITLE
Photon:  The type or namespace name could not be found

### ISSUE THREAD

**Issue by Anthmurphy95** [ColeChittim/PlayerPhysicsSync#1]
I'm sure this is a simple issue. Tried cloning the repo and opening it in Unity 2019.4.12f1. Is there something I am missing ?

![image](https://user-images.githubusercontent.com/74740505/99727079-5b0aa600-2aaf-11eb-8474-efcd21d62d34.png)

**Comment by ColeChittim** [comment]
Looks like the Photon libraries were not imported. A reimport of Pun 2 would fix this.
Overrode the .gitignore and this should be resolved. Let me know if this arises again.
